### ISSUE TITLE
quik_pipe

### ISSUE THREAD

**Issue by KirillV123** [boscogh/quik_pipe#1]
Добрый день! Вот я еще в этой теме написал Вам)
https://smart-lab.ru/blog/216370.php#comment9859473
Lua скрипт к терминалу подключил (помогла длл выложенная Вами в комментариях)
Буду теперь пробовать повторить реализацию pipe на python. Я как понимаю работа по следующему алгоритму осуществляется:
описываем необходимые функции в  lua скрипте (например отправка заявки и коллбеки), для этого используем описание всех функций в хелпе к квик. Затем записываем результаты выполнения функций в буфер, и передаем его в нашу внешнюю программу... Запросы информации из квика по такому же принципу формируем запрос и название функции, отправляем в скрипт на Lua, где в бесконечном цикле считывается название необходимой функции и отправляются в нее параметры.... 
Правильно я понял общую схему работы ?

Нашел на питон вот такую реализацию  named pipe:
`
import time
import sys
import win32pipe, win32file, pywintypes

def pipe_server():
    print("pipe server")
    count = 0
    pipe = win32pipe.CreateNamedPipe(
        r'\\.\pipe\Foo',
        win32pipe.PIPE_ACCESS_DUPLEX,
        win32pipe.PIPE_TYPE_MESSAGE | win32pipe.PIPE_READMODE_MESSAGE | win32pipe.PIPE_WAIT,
        1, 65536, 65536,
        0,
        None)
    try:
        print("waiting for client")
        win32pipe.ConnectNamedPipe(pipe, None)
        print("got client")

        while count < 10:
            print(f"writing message {count}")
            # convert to bytes
            some_data = str.encode(f"{count}")
            win32file.WriteFile(pipe, some_data)
            time.sleep(1)
            count += 1

        print("finished now")
    finally:
        win32file.CloseHandle(pipe)

def pipe_client():
    print("pipe client")
    quit = False

    while not quit:
        try:
            handle = win32file.CreateFile(
                r'\\.\pipe\Foo',
                win32file.GENERIC_READ | win32file.GENERIC_WRITE,
                0,
                None,
                win32file.OPEN_EXISTING,
                0,
                None
            )
            res = win32pipe.SetNamedPipeHandleState(handle, win32pipe.PIPE_READMODE_MESSAGE, None, None)
            if res == 0:
                print(f"SetNamedPipeHandleState return code: {res}")
            while True:
                resp = win32file.ReadFile(handle, 64*1024)
                print(f"message: {resp}")
        except pywintypes.error as e:
            if e.args[0] == 2:
                print("no pipe, trying again in a sec")
                time.sleep(1)
            elif e.args[0] == 109:
                print("broken pipe, bye bye")
                quit = True

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("need s or c as argument")
    elif sys.argv[1] == "s":
        pipe_server()
    elif sys.argv[1] == "c":
        pipe_client()
    else:
        print(f"no can do: {sys.argv[1]}")`

но пока еще не успел разобраться как следует и как это применить в данном конкретном примере.
 
И можете еще вот с этим подсказать:
https://smart-lab.ru/blog/216370.php#comment9860339

**Comment by boscogh** [comment]
пример клиента есть - в Java части, API стандартное Win

**Comment by KirillV123** [comment]
Данные получилось извлекать...  Я читал, что вы и заявки через pipe кидаете? По скорости приблизительно как и через библиотек trans2quik? И как понимаю функционал для работы с заявками в вашем примере не реализован, необходимо будет qlua скрипт дополнять функциями? И есть ли в qlua возможность отправлять транзакцию , проверить отправлена она или нет с полученным ordernumber(получить ответ как в reply_callback) a затем самостоятельно по номеру сделать запрос о ее статусе, не дожидаясь ответа в колбэк? Я просто не совсем понял канал pipe при запросе обновления стакана сразу же освобождает канал для новых команд , а затем по приходу события отправляет информацию...либо висит и ждёт пока придет колбэк, ничего не принимает и только по приходу события  передает данные

**Comment by boscogh** [comment]
нет, до отправки заявок руки пока так и не дошли. 
по lua есть справка в самом квике. там функционал аналогичный trans2quik, так и есть.
всё-таки лучше работать с колбэками, чем запрашивать самому - это куда менее затратно.

по стакану насколько две функции. одна ждёт пока в стакане случится изменение, вторая присылает его текущее состояние.

в канале буфера нет, всё работает в один поток, так что ожидание блокирует всю обработку.
